name: mypy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: mypy
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python 3.9
          uses: actions/setup-python@v5
          with:
            python-version: 3.9

        - name: Install Poetry
          uses: abatilo/actions-poetry@v3

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            poetry install --with dev
        
        - name: Run mypy
          run: make mypy